# PhonePe Automation Project

## Notebook 1: Data Understanding & Daily Data Generation

### Objective
Understand the original dataset and prepare the logic to generate 50 new transactions every day.

### Input
Original PhonePe Dataset

### Output
Daily Generated Dataset (50 Rows)

### Tools
- Python
- Pandas

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel("../data/raw/phonepe_dataset.xlsx")

In [4]:
df.head(10)

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
0,RCG_0C338474B366,926.59,PP0021371,Recharge_Bills,FASTag Recharge,Successful,Successful,09-06-2024
1,RCG_6B3B86B07A76,1211.64,PP0002388,Recharge_Bills,DTH,Successful,Successful,04-08-2024
2,RCG_767822392A0E,746.27,PP1101831,Recharge_Bills,Cable TV,Successful,Successful,19-02-2024
3,RCG_527E6AC74B11,1319.89,PP0033099,NaN,Mobile Recharge,Successful,Successful,22-12-2024
4,RCG_6B50A8C694E1,112.44,PP1059869,Recharge_Bills,Cable TV,Successful,Successful,07-09-2024
...,...,...,...,...,...,...,...,...
2045,RCG_3EE49C1D52E9,290.81,PP0006365,Recharge_Bills,FASTag Recharge,Successful,Successful,16-05-2024
2046,RCG_33F0CC673F58,1401.63,PP1077510,Recharge_Bills,DTH,Successful,Successful,04-01-2024
2047,RCG_F579A0CA89CC,1683.22,PP1064156,Recharge_Bills,FASTag Recharge,Successful,Successful,18-01-2024
2048,RCG_E392F6AA90F4,506.60,PP1052014,Recharge_Bills,Mobile Recharge,Successful,Successful,20-03-2024
2049,RCG_1F3A314FA40A,1653.27,PP0002097,Recharge_Bills,FASTag Recharge,Successful,Successful,16-09-2024

In [13]:
df.tail()

,Transaction ID,Amount,User ID,Service,Service Type,Payment_Status,Reason,Date
2045,RCG_3EE49C1D52E9,290.81,PP0006365,Recharge_Bills,FASTag Recharge,Successful,Successful,16-05-2024
2046,RCG_33F0CC673F58,1401.63,PP1077510,Recharge_Bills,DTH,Successful,Successful,04-01-2024
2047,RCG_F579A0CA89CC,1683.22,PP1064156,Recharge_Bills,FASTag Recharge,Successful,Successful,18-01-2024
2048,RCG_E392F6AA90F4,506.60,PP1052014,Recharge_Bills,Mobile Recharge,Successful,Successful,20-03-2024
2049,RCG_1F3A314FA40A,1653.27,PP0002097,Recharge_Bills,FASTag Recharge,Successful,Successful,16-09-2024

In [14]:
df.shape

(2050, 8)

In [15]:
df.columns

Index(['Transaction ID', 'Amount', 'User ID', 'Service', 'Service Type',
       'Payment_Status', 'Reason', 'Date'],
      dtype='str')

In [16]:
df.dtypes

Transaction ID        str
Amount            float64
User ID               str
Service               str
Service Type          str
Payment_Status        str
Reason                str
Date                  str
dtype: object

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  1988 non-null   str
 1   Amount          1988 non-null   float64
 2   User ID         1988 non-null   str
 3   Service         1988 non-null   str
 4   Service Type    1990 non-null   str
 5   Payment_Status  1988 non-null   str
 6   Reason          1988 non-null   str
 7   Date            1988 non-null   str
dtypes: float64(1), str(7)
memory usage: 128.3 KB

In [18]:
df.isnull().sum()

Transaction ID    62
Amount            62
User ID           62
Service           62
Service Type      60
Payment_Status    62
Reason            62
Date              62
dtype: int64

In [19]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Transaction ID: 1945
Amount: 1934
User ID: 1927
Service: 1
Service Type: 9
Payment_Status: 2
Reason: 4
Date: 418

# Analyze the Data Pattern

In [20]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique()[:10])  # First 10 unique values

Transaction ID
<StringArray>
['RCG_0C338474B366', 'RCG_6B3B86B07A76', 'RCG_767822392A0E',
 'RCG_527E6AC74B11', 'RCG_6B50A8C694E1', 'RCG_E63DCBDBB8C9',
 'RCG_DD16B3117FB9', 'RCG_654D31ECCDC2', 'RCG_6C53A7808151',
 'RCG_92AE572161FA']
Length: 10, dtype: str

Amount
[ 926.59 1211.64  746.27 1319.89  112.44 1278.95 1206.69 1945.11     nan
 1954.71]

User ID
<StringArray>
['PP0021371', 'PP0002388', 'PP1101831', 'PP0033099', 'PP1059869', 'PP1093720',
 'PP1067328', 'PP0041770', 'PP0017979', 'PP1085390']
Length: 10, dtype: str

Service
<StringArray>
['Recharge_Bills', nan]
Length: 2, dtype: str

Service Type
<StringArray>
[ 'FASTag Recharge',              'DTH',         'Cable TV',
  'Mobile Recharge',                nan, 'FASTag Recharge ',
 'Mobile Recharge ',             'DTH ',        'Cable TV ',
             'nan ']
Length: 10, dtype: str

Payment_Status
<StringArray>
['Successful', 'Failed', nan]
Length: 3, dtype: str

Reason
<StringArray>
['Successful', nan, 'Insufficient amount', 'Wrong PIN', 'Server error']
Length: 5, dtype: str

Date
<StringArray>
['09-06-2024', '04-08-2024', '19-02-2024', '22-12-2024', '07-09-2024',
 '25-07-2024', '06-08-2024', '23-04-2024', '25-06-2024', '20-11-2024']
Length: 10, dtype: str

In [22]:
df["Amount"].describe()

count    1988.000000
mean     1010.281861
std       575.981093
min        20.430000
25%       509.500000
50%      1020.885000
75%      1515.097500
max      1997.400000
Name: Amount, dtype: float64

In [23]:
print("Minimum Date :", df["Date"].min())
print("Maximum Date :", df["Date"].max())

Minimum Date : 01-01-2024
Maximum Date : 31-10-2024